replicaCount: 1

auth:
  rootPassword: rootpassword        # Mot de passe root de MariaDB
  database: taskmanager            # Nom de la base de données
  username: user                   # Nom d'utilisateur pour la DB
  password: password               # Mot de passe de l'utilisateur DB

# Configuration de Galera MariaDB
#galera:
#  bootstrap:
#    bootstrapFromNode: "my-galera-mariadb-galera-0"  # Le nœud à partir duquel la réplication doit commencer

# Configuration des volumes persistants
primary:
  persistence:
    enabled: true
    size: 5Gi                      # Taille du volume pour le nœud primaire

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    size: 5Gi                      # Taille des volumes pour les réplicas secondaires

# Configuration du service MariaDB
#service:
#  type: ClusterIP                  # Type de service pour MariaDB
#  ports:
#    mysql: 3306                     # Port d'accès à MariaDB

# Configuration des ressources pour l'application backend
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m

# Image Docker pour le backend de l'application
image:
  repository: yacine78/taskmanager  # Nom de l'image Docker pour le backend
  tag: latest                              # Version de l'image
  pullPolicy: Always                 # Politique de téléchargement de l'image

# Configuration du service backend
service:
  type: LoadBalancer                # Utilisation de LoadBalancer avec MetalLB
  port: 80                           # Port d'accès au service backend

# Variables d'environnement pour la connexion à la base de données
env:
  DB_HOST: galeradb-mariadb-galera.taskmanager.svc.cluster.local  # Nom du service MariaDB
  DB_USER: user                     # Utilisateur DB
  DB_PASSWORD: password             # Mot de passe DB
  DB_NAME: taskmanager              # Nom de la base de données